# Generated by Django 6.0.6 on 2026-07-18 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], db_index=True, default='QUEUED', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_job_status'), models.Index(fields=['-created_at'], name='idx_job_created')],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('frame_index', models.IntegerField()),
                ('label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('image_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='backend.videojob')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['job', 'timestamp'], name='idx_det_job_ts')],
            },
        ),
    ]
